name: HACS Validation
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
