name: Validate with HACS

on:
  pull_request: {}
  push:
    branches: [ main ]

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: Validate HACS Integration
    steps:
      - uses: actions/checkout@v4

      - uses: hacs/action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          category: integration
          repository: ${{ github.repository }}
