name: Validate HACS

on:
  pull_request:
  push:

jobs:
  validate:
    name: Validate HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
          repository: tzachb/Homeseer-HA
