# .github/workflows/hacs.yaml
name: Validate HACS Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hacs/action@main
        with:
          category: integration
          repository: tzachb/Homeseer-HA
